#Banco de Dados
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

#Token
jwt.signature=${TOKEN_PRIVATE_KEY}
jwt.expirationTime=${TOKEN_EXPIRATION_TIME}

#Email
default.sender=${EMAIL_USERNAME}