spring.datasource.url=jdbc:postgresql://localhost:5432/db_controle_financeiro
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

jwt.signature=13741f5f-6802-4c7a-b010-608088368410
jwt.expirationTime=10800000